import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Providers } from "./providers";
import { Toaster } from "sonner";
import Header from "../components/header";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en" suppressHydrationWarning>
        <body className="bg-gray dark:bg-[#1E1E1E] text-black dark:text-white relative font-GMSans z-50">
          <Toaster />
          <Providers>
            <Navbar />
            <div className="px-5 pt-24">{children}</div>
          </Providers>
        </body>
      </html>
    </SessionProvider>
  );
}
